Open pull request
Gallaann/cpp_task1 pull request #2
Opened 2023-03-13 17:13 UTC by Gallaann

## Task 1

Made by Vladimir Zakharov 
WEB-11
Mentor - Arseniy Evdokimov
___
Программа должна принимать необходимые для работы имена распакованных файлов в качестве аргументов командной строки и выводить данные в стандартный вывод.  
Программа не должна брать в расчет фильмы для взрослых, и , если в варианте используется рейтинг, не должна учитывать рейтинг фильмов с числом оценок меньше 1000.  
Программа не должна использовать интерактивный ввод с клавиатуры, например, "введите имя файла", "введите необходимый год", "ведите q чтобы выйти" - такими программами не удобно пользоваться и их разработка занимает больше времени.  
  
Ваш вариант:  
Вывести русские названия (при наличии) всех фильмов, в которых актер играет персонажа, имя которого переданно в аргументах командной строки

2023-04-02 11:44 UTC, Arugaf requested changes
Нет преподавателя в репозитории.

Коммиты достаточно атомарны, но в сообщении к ним написано то, что было сделано, вместо зачем это было сделано.

Нет clang-format, cpplint, санитайзеров, юнит- и интеграционных тестов (и, соответственно, отчета о покрытии).

Не используются именованные и анонимные неймспейсы, constexpr/const/noexcept спецификаторы там, атрибуты где это применимо.

Кажется, что не хватает гибкости (нельзя подставлять различные значения параметров).

Пока 0/10.

2023-04-02 11:44 UTC, Arugaf commented on .github/workflows/ci.yml
> +          path: .
А где это дальше используется?

2023-04-02 11:44 UTC, Arugaf commented on CMakeLists.txt
> +project(Task1)
Где переменная?

2023-04-02 11:44 UTC, Arugaf commented on CMakeLists.txt
> +add_library(title_by_character_finder src/title_by_character_finder.cpp)
Где соответствующие переменные под исходники?

2023-04-02 11:44 UTC, Arugaf commented on CMakeLists.txt
> +add_library(title_by_character_finder src/title_by_character_finder.cpp)
Почему два отдельных бинаря собираются в одном cmake файле?

2023-04-02 11:44 UTC, Arugaf commented on CMakeLists.txt
> +target_include_directories(title_by_character_finder PUBLIC include)
Почему паблик?

2023-04-02 11:44 UTC, Arugaf commented on include/title_by_character_finder.h
> +#include <string>
В алфавитном порядке.

2023-04-02 11:44 UTC, Arugaf commented on include/title_by_character_finder.h
> +    bool static getInputStream(std::stringstream &input_stream, const std::string &path_to_file);
Чем обусловлено наличие пустой строки между каждым из методов/полей?

2023-04-02 11:44 UTC, Arugaf commented on include/title_by_character_finder.h
> +    bool ParseID(const std::string &path, const std::string &character_name);
Лучше & и * прицепить к типу, а не к имени.

2023-04-02 11:44 UTC, Arugaf commented on include/title_by_character_finder.h
> +    bool ParseLocalizedTitle(const std::string &path);
Почему bool?

2023-04-02 11:44 UTC, Arugaf commented on include/title_by_character_finder.h
> +    void PrintResult() const;
Перегруженный оператор?

2023-04-02 11:44 UTC, Arugaf commented on include/title_by_character_finder.h
> +    bool static findColumns(std::string &columns_naming_line, std::unordered_map<std::string, int> &column_names_map);
Почему static?

2023-04-02 11:44 UTC, Arugaf commented on include/title_by_character_finder.h
> +    bool static findColumns(std::string &columns_naming_line, std::unordered_map<std::string, int> &column_names_map);
Не используем snake_case.

2023-04-02 11:44 UTC, Arugaf commented on include/title_by_character_finder.h
> +    bool static getInputStream(std::stringstream &input_stream, const std::string &path_to_file);
Сначала методы, потом поля. С указанием модификаторов доступа для каждой **группы**.

2023-04-02 11:44 UTC, Arugaf commented on main.cpp
> +    if (argc != 5) {
Хардкод.

2023-04-02 11:44 UTC, Arugaf commented on main.cpp
> +        return 1;
Магическая константа.

2023-04-02 11:44 UTC, Arugaf commented on main.cpp
> +    movie_titles.PrintResult();
Хардкод.

2023-04-02 11:44 UTC, Arugaf commented on main.cpp
> +    return 0;
Почему какая-то бизнес-логика в main?

2023-04-02 11:44 UTC, Arugaf commented on main.cpp
> +    MovieTitles movie_titles;
Нужен явный вызов дефолтного конструктора через `{}`.

2023-04-02 11:44 UTC, Arugaf commented on main.cpp
> +    movie_titles.PrintResult();
Кажется, что должны быть какие-то проверки на ошибки/валидность данных?

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +#include "title_by_character_finder.h"
Сначала парный хедер, затем уже библиотечные.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +bool MovieTitles::ParseID(const std::string &path, const std::string &character_name) {
`std::filesystem::path`

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +bool MovieTitles::ParseID(const std::string &path, const std::string &character_name) {
Непонятное название метода.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +    getInputStream(input_stream, path);
Почему так?

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +                                                       {"tconst",     0}};
В анонимный неймспейс и константой, чтобы не загрязнять метод.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +        std::cerr << "Error: not enough columns in file." << std::endl;
Почему внутренний метод знает о стандартном потоке ошибок?

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +        std::cerr << "Error: not enough columns in file." << std::endl;
Без точки в конце.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +        return false;
Почему булево значение? Либо enum, либо structured binding.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +    }
Нехороший цикл. Надо разбивать.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +    while (std::getline(input_stream, line)) {
Стремимся к идиоме "No raw loops".

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +        std::size_t i = 0;
Ни о чем не говорящее название переменной.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +        std::stringstream cur_line(line);
Зачем сокращение? Тут тоже символы по талонам выдают?

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +            i++;
Префиксный инкремент >> постфиксного.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +            if (i == column_map["tconst"]) {
Стараемся не указывать имя типа в переменной.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +            if (i == column_map["tconst"]) {
Неудачное применение оператора `[]`.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +            m_titles[movie_id];
?

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +bool MovieTitles::ParsePrimaryTitle(const std::string &path) {
Не нравится имена методов.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +        }
Нечитаемый цикл.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +            m_titles[movie_id] = movie_title;
В целом не советую в таких кейсах использовать оператор квадратных скобках (почему можно прочитать в документации).

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +        std::string movie_type;
Кажется, что метод знает слишком много.

Схему надо вынести в какую-то структуру.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +        }
Стараемся не использовать else.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +        std::cout << container.second << std::endl;
Почему метод знает про стандартный поток вывода?

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +bool MovieTitles::getInputStream(std::stringstream &input_stream, const std::string &path_to_file) {
Странная функция какая-то.

2023-04-02 11:44 UTC, Arugaf commented on src/title_by_character_finder.cpp
> +}
В целом те же самые ошибки как и до этого.

2023-04-08 22:53 UTC, Gallaann commented
Сорри, забыл здесь отписать, жду ревью

2023-12-05 11:55 UTC, closed without merging